[package]
name = "day08"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"

[dependencies]
tikv-jemallocator = "0.5.0"

[build]
rustflags = ["-C", "target-cpu=native"]
